name: more_experts
description: "MoRe Experts Client Management App"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0

  # State Management
  provider: ^6.1.1

  # UI & Utilities
  google_fonts: ^6.1.0
  flutter_animate: ^4.3.0
  intl: ^0.19.0
  cupertino_icons: ^1.0.2
  mongo_dart: ^0.10.5
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
